Diplom/Controllers/FileTasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Diplom.Models;
using Diplom.Data;

namespace Diplom.Controllers
{
    public class FileTasksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FileTasksController(ApplicationDbContext context)
        {
            _context = context;
            _context.Zadachis.Load();
        }

        // GET: FileTasks
        public async Task<IActionResult> Index()
        {
            var diplomContext = _context.FileTask.Include(f => f.TaskDistribution);
            return View(await diplomContext.ToListAsync());
        }

        // GET: FileTasks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fileTask = await _context.FileTask
                .Include(f => f.TaskDistribution)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fileTask == null)
            {
                return NotFound();
            }

            return View(fileTask);
        }

        // GET: FileTasks/Create
        public IActionResult Create()
        {
            ViewData["TaskDistributionId"] = new SelectList(_context.TaskDistributions, "Id", "View");
            return View();
        }

        // POST: FileTasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Path_File,File_Detail,TaskDistributionId")] FileTask fileTask)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fileTask);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TaskDistributionId"] = new SelectList(_context.TaskDistributions, "Id", "View", fileTask.TaskDistributionId);
            return View(fileTask);
        }

        // GET: FileTasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fileTask = await _context.FileTask.FindAsync(id);
            if (fileTask == null)
            {
                return NotFound();
            }
            ViewData["TaskDistributionId"] = new SelectList(_context.TaskDistributions, "Id", "View", fileTask.TaskDistributionId);
            return View(fileTask);
        }

        // POST: FileTasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Path_File,File_Detail,TaskDistributionId")] FileTask fileTask)
        {
            if (id != fileTask.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fileTask);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FileTaskExists(fileTask.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TaskDistributionId"] = new SelectList(_context.TaskDistributions, "Id", "View", fileTask.TaskDistributionId);
            return View(fileTask);
        }

        // GET: FileTasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fileTask = await _context.FileTask
                .Include(f => f.TaskDistribution)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fileTask == null)
            {
                return NotFound();
            }

            return View(fileTask);
        }

        // POST: FileTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fileTask = await _context.FileTask.FindAsync(id);
            _context.FileTask.Remove(fileTask);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FileTaskExists(int id)
        {
            return _context.FileTask.Any(e => e.Id == id);
        }
    }
}

Diplom/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Diplom.Models;
using Diplom.Data;
using Microsoft.AspNetCore.Http;


namespace Diplom.Controllers
{
    public class HomeController : Controller
    {
        public HomeController(ApplicationDbContext context)
        {
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SetTheme(string data)
        {
            CookieOptions cookies = new CookieOptions();
            cookies.Expires = DateTime.Now.AddDays(1);

            Response.Cookies.Append("theme", data, cookies);

            return Ok();
        }

    }
}

Diplom/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Diplom.Data;
using Diplom.Models;
using Microsoft.AspNetCore.Identity;

namespace Diplom.Controllers
{
    public class RolesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(ApplicationDbContext context, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _roleManager = roleManager;
        }

        // GET: Roles
        public async Task<IActionResult> Index()
        {
            var c = await _roleManager.Roles.ToListAsync();
            return View(c);
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string Name)
        {

            if (ModelState.IsValid)
            {
                await _roleManager.CreateAsync(new IdentityRole(Name));
                return RedirectToAction(nameof(Index));
            }
            return View(Name);
        }

        // GET: Roles/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id,  string Name)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var role = await _roleManager.FindByIdAsync(id);

            if (ModelState.IsValid)
            {
                try
                {
                    role.Name = Name;
                    await _roleManager.UpdateAsync(role);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var role = await _context.Roles.FindAsync(id);
            _context.Roles.Remove(role);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(string id)
        {
            return _context.Roles.Any(e => e.Id == id);
        }
    }
}

Diplom/Controllers/StatusesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Diplom.Models;
using Diplom.Data;

namespace Diplom.Controllers
{
    public class StatusesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StatusesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Statuses
        public async Task<IActionResult> Index()
        {
            return View(await _context.Statuses.ToListAsync());
        }

        // GET: Statuses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Statuses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        // GET: Statuses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Statuses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Status_name")] Status status)
        {
            if (ModelState.IsValid)
            {
                _context.Add(status);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }

        // GET: Statuses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Statuses.FindAsync(id);
            if (status == null)
            {
                return NotFound();
            }
            return View(status);
        }

        // POST: Statuses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Status_name")] Status status)
        {
            if (id != status.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(status);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StatusExists(status.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }

        // GET: Statuses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Statuses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        // POST: Statuses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var status = await _context.Statuses.FindAsync(id);
            _context.Statuses.Remove(status);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StatusExists(int id)
        {
            return _context.Statuses.Any(e => e.Id == id);
        }
    }
}

Diplom/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager


<body>
    
    @if (!SignInManager.IsSignedIn(User))
    {
        <br />
         <div class="text-center">
            <image height="25%" width="25%" src="https://www.college-edu.ru/upload/medialibrary/d2e/d2e35f185d294878179d5a0f2a6c9f3d.png"></image>

        </div>
        <div class="text-center">
            <p class="text-center colortext" style="margin-top: 30%; font:bold; font-size:48px; margin-top: 0;">
                Для работы с веб ресурсом, пожалуйста авторизуйтесь
            </p>
            <a type="button" class="btn btn-lg  br0 btn-outline-dark" asp-area="Identity" asp-page="/Account/Login">Войти</a>
            <a type="button" class="btn btn-lg br0 btn-outline-dark" asp-area="Identity" asp-page="/Account/Register">Регистрация</a>
            
        </div>
    }
    else
    {
    <main role="main">
        <div class="album py-5 ">
            <div class="container">

                <div class="row">
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm text-center">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Роли</h4>
                            </div>
                            <div class="card-body" bgcolor="#c1d5e0">
                                <image height="25%" width="25%" src="https://image.flaticon.com/icons/png/512/126/126472.png"></image>

                                <a type="button" asp-action="Index" asp-controller="Roles" class="btn btn-lg btn-block br0 btn-secondary">Подробнее</a>

                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm text-center">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Функции ИС</h4>
                            </div>
                            <div class="card-body">
                                <image height="25%" width="25%" src="https://image.flaticon.com/icons/png/512/117/117924.png"></image>
                                <a type="button" asp-action="Index" asp-controller="Functions" class="btn btn-lg btn-block br0 btn-secondary">Подробнее</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm text-center">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Управление ролями</h4>
                            </div>
                            <div class="card-body">
                                <image height="25%" width="25%" src="https://image.flaticon.com/icons/png/512/126/126318.png"></image>
                                <a type="button" asp-action="Index" asp-controller="RoleManagment" class="btn btn-lg btn-block br0 btn-secondary">Подробнее</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm text-center">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Сотрудники</h4>
                            </div>
                            <div class="card-body">
                                <image height="25%" width="25%" src="https://image.flaticon.com/icons/png/512/84/84936.png"></image>
                                <a type="button" asp-action="Index" asp-controller="Employees" class="btn btn-lg btn-block br0 btn-secondary">Подробнее</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm text-center">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Должности</h4>
                            </div>
                            <div class="card-body">
                                <image height="25%" width="25%" src="https://image.flaticon.com/icons/png/512/126/126197.png"></image>
                                <a type="button" asp-action="Index" asp-controller="Positions" class="btn btn-lg btn-block br0 btn-secondary">Подробнее</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm text-center">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Должности сотрудника</h4>
                            </div>
                            <div class="card-body">
                                <image height="25%" width="25%" src="https://image.flaticon.com/icons/png/512/126/126423.png"></image>
                                <a type="button" asp-action="Index" asp-controller="Pluralities" class="btn btn-lg btn-block br0 btn-secondary">Подробнее</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm text-center">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Учетная Запись</h4>
                            </div>
                            <div class="card-body">
                                <image height="25%" width="25%" src="https://image.flaticon.com/icons/png/512/61/61205.png"></image>
                                <a type="button" asp-action="Index" asp-controller="Account" class="btn btn-lg btn-block br0 btn-secondary">Подробнее</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm text-center">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Статус задач</h4>
                            </div>
                            <div class="card-body">
                                <image height="25%" width="25%" src="https://image.flaticon.com/icons/png/512/37/37921.png"></image>
                                <a type="button" asp-action="Index" asp-controller="Statuses" class="btn btn-lg btn-block br0 btn-secondary">Подробнее</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm text-center">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Задача</h4>
                            </div>
                            <div class="card-body">
                                <image height="25%" width="25%" src="https://image.flaticon.com/icons/png/512/51/51841.png"></image>
                                <a type="button" asp-action="Index" asp-controller="Zadachis" class="btn btn-lg btn-block br0 btn-secondary">Подробнее</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm text-center">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Распределение задач</h4>
                            </div>
                            <div class="card-body">
                                <image height="25%" width="25%" src="https://image.flaticon.com/icons/png/512/126/126549.png"></image>
                                <a type="button" asp-action="Index" asp-controller="TaskDistributions" class="btn btn-lg btn-block br0 btn-secondary">Подробнее</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm text-center">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Вид комментария</h4>
                            </div>
                            <div class="card-body">
                                <image height="25%" width="25%" src="https://image.flaticon.com/icons/png/512/14/14501.png"></image>
                                <a type="button" asp-action="Index" asp-controller="TypeComments" class="btn btn-lg btn-block br0 btn-secondary">Подробнее</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm text-center">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Комментарии к задаче</h4>
                            </div>
                            <div class="card-body">
                                <image height="25%" width="25%" src="https://image.flaticon.com/icons/png/512/60/60782.png"></image>
                                <a type="button" asp-action="Index" asp-controller="TaskComments" class="btn btn-lg btn-block br0 btn-secondary">Подробнее</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm text-center">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">Файлы к задаче</h4>
                            </div>
                            <div class="card-body">
                                <image height="25%" width="25%" src="https://image.flaticon.com/icons/png/512/130/130291.png"></image>
                                <a type="button" asp-action="Index" asp-controller="FileTasks" class="btn btn-lg btn-block br0 btn-secondary">Подробнее</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



    </main>
    }
  
</body>